chr: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22","X"]
maf: [0.005,0.001,0.0005,0.00025,0.0001]
ppttmm: ["basic",]

#ppttmm:["basic", "dbptm","qptm","basic_qptm","basic_dbptm","basic_all"]