folds: ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12"]
#folds: ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12","ori"]
types: ["ANCESTRY","CENTER","ORIGIN","SEQ_KIT","CANCER","GENDER","SAM_LOWQUAL","SEQ_LOWQUAL"]

#folds: ["0"]