#chr: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22","X"]
maf: [0.005,0.001,0.0005,0.00025,0.0001]
revie: [2,1]
#cancer: ["ACC", "BLCA","BRCA", "CESC", "CHOL", "COADREAD", "DLBC", "ESCA", "GBM", "HNSC", "KICH", "KIRC", "KIRP", "LAML", "LGG" , "LIHC", "LUAD", "LUSC", "MESO", "OV", "PAAD", "PCPG", "PRAD", "SARC", "SKCM", "STAD", "TGCT", "THCA", "THYM", "UCEC",  "UCS", "UVM"]
cancer: ["BRCA"]